#ifndef _SIGNATURES_H_
#define _SIGNATURES_H_

/* This file is auto generated */
/* Chunk IDs are created by using cksum on signature names */
/* Hence, please do not change signature names */

#define  SIG_CHANNEL                                         0x7EC2A570
#define  SIG_CHANNEL_IMAGE                                   0x4EEB9C3F
#define  SIG_CHANNEL_PROCEDURAL                              0xFFC16160
#define  SIG_CHANNEL_PROCEDURAL_BRICK                        0xFA7B27F9
#define  SIG_CHANNEL_PROCEDURAL_BRICK_COLORS                 0x994D644E
#define  SIG_CHANNEL_PROCEDURAL_BRICK_GEOMETRY               0x608C2AA8
#define  SIG_CHANNEL_PROCEDURAL_CHESS                        0x693BF181
#define  SIG_CHANNEL_PROCEDURAL_CHESS_COLORS                 0x5CF5F21C
#define  SIG_CHANNEL_PROCEDURAL_CHESS_GEOMETRY               0x391F1ECF
#define  SIG_CHANNEL_PROCEDURAL_GRADIENT                     0xAA7D765A
#define  SIG_CHANNEL_PROCEDURAL_GRADIENT_COLORS              0x4BAA5A7E
#define  SIG_CHANNEL_PROCEDURAL_GRADIENT_GEOMETRY            0xCC1DA528
#define  SIG_CHANNEL_PROCEDURAL_NOISE                        0x5555DA0A
#define  SIG_CHANNEL_PROCEDURAL_NOISE_COLORPAIR_COUNT        0x1008CAAB
#define  SIG_CHANNEL_PROCEDURAL_NOISE_COLORPAIRS             0x79814FB5
#define  SIG_CHANNEL_PROCEDURAL_NOISE_GRADIENTS              0xF33D8529
#define  SIG_CHANNEL_PROCEDURAL_NOISE_INTERPOLATION          0xDB77D998
#define  SIG_CHANNEL_PROCEDURAL_NOISE_OCTAVES                0x961160AB
#define  SIG_CHANNEL_PROCEDURAL_NOISE_THRESHOLDS             0xBF93F08B
#define  SIG_CHANNEL_PROCEDURAL_RESOLUTION                   0xEE216EAF
#define  SIG_CHANNEL_SOLID                                   0x6393699E
#define  SIG_EXTENSION_ENTRY                                 0xE4C94E11
#define  SIG_EXTENSIONS                                      0x22457A87
#define  SIG_MATERIAL_ALPHA                                  0x563A65EF
#define  SIG_MATERIAL_ALPHA_OPACITY                          0x84E8FA21
#define  SIG_MATERIAL_BUMP                                   0x9679768A
#define  SIG_MATERIAL_BUMP_STRENGTH                          0x2A823612
#define  SIG_MATERIAL_DIFFUSE                                0xAF327CA2
#define  SIG_MATERIAL_DISPLACEMENT                           0xA094CAED
#define  SIG_MATERIAL_DISPLACEMENT_STRENGTH                  0x0FB07028
#define  SIG_MATERIAL_ENTRY                                  0xD8A97057
#define  SIG_MATERIAL_FLAGS                                  0x8FD3FEB1
#define  SIG_MATERIAL_NAME                                   0x9B8F73CE
#define  SIG_MATERIAL_REFLECTION                             0x2ED1D57E
#define  SIG_MATERIAL_REFLECTION_STRENGTH                    0xA6E27549
#define  SIG_MATERIAL_REFRACTION                             0xF7116533
#define  SIG_MATERIAL_REFRACTION_STRENGTH                    0xDBF22C46
#define  SIG_MATERIALS                                       0x09ABD5AC
#define  SIG_MATERIAL_SPECULAR                               0xCE7F7484
#define  SIG_MATERIAL_SPECULAR_LEVEL                         0x24CA1ADB
#define  SIG_MATERIAL_SPECULAR_SHININESS                     0x92BEF4DC
#define  SIG_OBJECT_ACTIVE                                   0x1E4FEB75
#define  SIG_OBJECT_BONE                                     0x58B4AB43
#define  SIG_OBJECT_BONE_FIXING                              0x37806762
#define  SIG_OBJECT_BONE_FIXING_TRANSFORMATION               0xEF18142E
#define  SIG_OBJECT_BONE_LENGTH                              0xB876D5B8
#define  SIG_OBJECT_BONE_RIG_BINDMATRIX                      0xC9223A6B
#define  SIG_OBJECT_BONE_RIG_ENTRY                           0x0BED790B
#define  SIG_OBJECT_BONE_RIGS                                0x6A4F8B22
#define  SIG_OBJECT_BONE_RIG_SKIN                            0x8447FACC
#define  SIG_OBJECT_BONE_RIG_SKINMATRIX                      0xA610F6C4
#define  SIG_OBJECT_BONE_RIG_WEIGHTGROUP_ENTRY               0xA05CE85C
#define  SIG_OBJECT_BONE_RIG_WEIGHTGROUPS                    0x2F6656B6
#define  SIG_OBJECT_CAMERA                                   0x590154D0
#define  SIG_OBJECT_CAMERA_FOCAL                             0x3B0925B4
#define  SIG_OBJECT_DECLARE_BONE                             0xD38F2479
#define  SIG_OBJECT_DECLARE_CAMERA                           0x7BA0BFB8
#define  SIG_OBJECT_DECLARE_CUBE                             0x1D993B1E
#define  SIG_OBJECT_DECLARE_CYLINDER                         0xCAA14CDF
#define  SIG_OBJECT_DECLARE_ENTRY                            0xDD427B41
#define  SIG_OBJECT_DECLARE_FFD                              0x1502C03D
#define  SIG_OBJECT_DECLARE_INSTANCE                         0x987151B2
#define  SIG_OBJECT_DECLARE_LIGHT                            0x42AA0B96
#define  SIG_OBJECT_DECLARE_MESH                             0x3EFDBC75
#define  SIG_OBJECT_DECLARE_MORPHER                          0xFAA1162D
#define  SIG_OBJECT_DECLARE_NULL                             0x85495C2F
#define  SIG_OBJECT_DECLARE_PARTICLEEMITTER                  0x396F2EA1
#define  SIG_OBJECT_DECLARE_PLANE                            0xF7A64E65
#define  SIG_OBJECT_DECLARE_SCENE                            0x9E333C7D
#define  SIG_OBJECT_DECLARE_SKIN                             0x4E3C0F6F
#define  SIG_OBJECT_DECLARE_SPHERE                           0x0FB70D2A
#define  SIG_OBJECT_DECLARE_SPLINE                           0x700145E3
#define  SIG_OBJECT_DECLARE_SPLINEREVOLVER                   0x742529BD
#define  SIG_OBJECT_DECLARE_SUBDIVIDER                       0x20D0A5D8
#define  SIG_OBJECT_DECLARE_SYMMETRY                         0x174EF613
#define  SIG_OBJECT_DECLARE_TEXT                             0xC76424CA
#define  SIG_OBJECT_DECLARE_TORUS                            0xCC576620
#define  SIG_OBJECT_DECLARE_TUBE                             0xEA00D341
#define  SIG_OBJECT_DECLARE_WIREFRAME                        0x513D8878
#define  SIG_OBJECT_ENTRY                                    0x08CAC424
#define  SIG_OBJECT_FFD                                      0xAAB09BB7
#define  SIG_OBJECT_FFD_GEOMETRY                             0x3E1B16CA
#define  SIG_OBJECT_FFD_UVW                                  0x96C70372
#define  SIG_OBJECT_IDENTITY                                 0xFE404903
#define  SIG_OBJECT_IDENTITY_ID                              0x305704D7
#define  SIG_OBJECT_IDENTITY_PARENT                          0x34D92405
#define  SIG_OBJECT_IDENTITY_TYPE                            0x5173F267
#define  SIG_OBJECT_INSTANCE                                 0x2E6B3BA2
#define  SIG_OBJECT_INSTANCE_MIRRORED                        0x2A4DF614
#define  SIG_OBJECT_INSTANCE_MIRRORINGPLANE                  0x69CFADF9
#define  SIG_OBJECT_INSTANCE_REFERENCE                       0x8D71BF22
#define  SIG_OBJECT_KEY_DATA                                 0x577054D2
#define  SIG_OBJECT_KEY_DATA_LIGHT                           0x7B93AC07
#define  SIG_OBJECT_KEY_DATA_MORPHER                         0xDF460185
#define  SIG_OBJECT_KEY_DATA_MORPHER_SLOT_ENTRY              0xFCC8B531
#define  SIG_OBJECT_KEY_DATA_MORPHER_SLOT_ID                 0xDC52A02D
#define  SIG_OBJECT_KEY_DATA_MORPHER_SLOT_OPTIONS            0xDE59024D
#define  SIG_OBJECT_KEY_DATA_MORPHER_SLOT_OPTIONS_RATE       0x8A5ABB23
#define  SIG_OBJECT_KEY_DATA_MORPHER_SLOTS                   0x603888CC
#define  SIG_OBJECT_KEY_DATA_PARTICLEEMITTER                 0xBFA6FAA5
#define  SIG_OBJECT_KEY_ENTRY                                0xAA0C1CF8
#define  SIG_OBJECT_KEY_FLAGS                                0xFD76921E
#define  SIG_OBJECT_KEY_FLAGS_DATA                           0xC88F404E
#define  SIG_OBJECT_KEY_FLAGS_ROTATION                       0x3BCBC4FF
#define  SIG_OBJECT_KEY_FLAGS_SCALING                        0x7C3112B2
#define  SIG_OBJECT_KEY_FLAGS_TRANSLATION                    0x65E5E57B
#define  SIG_OBJECT_KEY_LOOP                                 0x0FEC17BD
#define  SIG_OBJECT_KEYS                                     0xBBE0F54D
#define  SIG_OBJECT_KEY_TRANSFORMATION                       0x499C5B71
#define  SIG_OBJECT_LIGHT                                    0x9722B4F3
#define  SIG_OBJECT_LIGHT_AMBIENT                            0x5857EAF8
#define  SIG_OBJECT_LIGHT_DIFFUSE                            0x95B25CFB
#define  SIG_OBJECT_LIGHT_INTENSITY                          0x482032B2
#define  SIG_OBJECT_LIGHT_SHADOW                             0xF365A4D5
#define  SIG_OBJECT_LIGHT_SHADOW_CASTING                     0xB34778F4
#define  SIG_OBJECT_LIGHT_SHADOW_COLOR                       0x45301A77
#define  SIG_OBJECT_LIGHT_SHADOW_SOFT                        0x51E1FCC7
#define  SIG_OBJECT_LIGHT_SHADOW_SOFT_RADIUS                 0x4137BDFA
#define  SIG_OBJECT_LIGHT_SHADOW_SOFT_SAMPLING               0xA09F9A46
#define  SIG_OBJECT_LIGHT_SPECULAR                           0x4F876F5D
#define  SIG_OBJECT_LIGHT_SPOT                               0x94A8DF01
#define  SIG_OBJECT_MESH                                     0xB5C6334F
#define  SIG_OBJECT_MESH_FACEGROUP_ENTRY                     0xE78FE5CD
#define  SIG_OBJECT_MESH_FACEGROUP_FACES                     0x303DDFB0
#define  SIG_OBJECT_MESH_FACEGROUP_NAME                      0xA7956F45
#define  SIG_OBJECT_MESH_FACEGROUPS                          0x0FB5B31E
#define  SIG_OBJECT_MESH_GEOMETRY                            0xB8E24649
#define  SIG_OBJECT_MESH_GEOMETRY_EDGES                      0x88CD116B
#define  SIG_OBJECT_MESH_GEOMETRY_POLYGONS                   0x66659F93
#define  SIG_OBJECT_MESH_GEOMETRY_POLYGONS_WITH_EDGES        0xDF4E0506
#define  SIG_OBJECT_MESH_GEOMETRY_VERTICES                   0xDC54DB9D
#define  SIG_OBJECT_MESH_GOURAUDLIMIT                        0xB1312AD6
#define  SIG_OBJECT_MESH_WEIGHTGROUP_ENTRY                   0x2038ABB8
#define  SIG_OBJECT_MESH_WEIGHTGROUP_NAME                    0x5ABC431A
#define  SIG_OBJECT_MESH_WEIGHTGROUPS                        0x48A48DC1
#define  SIG_OBJECT_MESH_WEIGHTGROUP_WEIGHTS                 0x41E78C3A
#define  SIG_OBJECT_MORPHER                                  0x66AB5D49
#define  SIG_OBJECT_MORPHER_MESHPOSE_ENTRY                   0x36A725F1
#define  SIG_OBJECT_MORPHER_MESHPOSE_GEOMETRY                0x889B5F26
#define  SIG_OBJECT_MORPHER_MESHPOSE_NAME                    0x6973ADDF
#define  SIG_OBJECT_MORPHER_MESHPOSES                        0xDFAC03AC
#define  SIG_OBJECT_MORPHER_MESHPOSE_SLOT_ID                 0x9FCAD991
#define  SIG_OBJECT_MORPHER_MESHPOSE_SLOT_ID64               0x56F4F24C
#define  SIG_OBJECT_MORPHER_RESETPOSITIONS                   0x14792184
#define  SIG_OBJECT_MORPHER_VERTEX_COUNT                     0xD1AA812A
#define  SIG_OBJECT_NOSHADING                                0xF717F39F
#define  SIG_OBJECT_NULL                                     0x0E72D315
#define  SIG_OBJECT_PARTICLEEMITTER                          0xC374A9A9
#define  SIG_OBJECT_PARTICLEEMITTER_DISPLAYPARTICLES         0xB2B55470
#define  SIG_OBJECT_PARTICLEEMITTER_ENDAT                    0xAC2CC9A1
#define  SIG_OBJECT_PARTICLEEMITTER_FINAL_ACCELERATION       0x316B1AE2
#define  SIG_OBJECT_PARTICLEEMITTER_FINAL_ROTATION           0xDD89B95A
#define  SIG_OBJECT_PARTICLEEMITTER_FINAL_SCALING            0x6B37E6D3
#define  SIG_OBJECT_PARTICLEEMITTER_FINAL_SPEED              0x60689D61
#define  SIG_OBJECT_PARTICLEEMITTER_FINAL_TRANSPARENCY       0xA9FD1F1E
#define  SIG_OBJECT_PARTICLEEMITTER_INITIAL_ACCELERATION     0xCC7FD2FC
#define  SIG_OBJECT_PARTICLEEMITTER_INITIAL_ROTATION         0x567E68A7
#define  SIG_OBJECT_PARTICLEEMITTER_INITIAL_SCALING          0xA856AC67
#define  SIG_OBJECT_PARTICLEEMITTER_INITIAL_SPEED            0x5227C15D
#define  SIG_OBJECT_PARTICLEEMITTER_INITIAL_TRANSPARENCY     0x54E9D700
#define  SIG_OBJECT_PARTICLEEMITTER_INITIALVAR_ACCELERATION  0x4DEBB23E
#define  SIG_OBJECT_PARTICLEEMITTER_INITIALVAR_ROTATION      0xF047B05E
#define  SIG_OBJECT_PARTICLEEMITTER_INITIALVAR_SCALING       0xDE90D929
#define  SIG_OBJECT_PARTICLEEMITTER_INITIALVAR_SPEED         0x724E082B
#define  SIG_OBJECT_PARTICLEEMITTER_INITIALVAR_TRANSPARENCY  0xD57DB7C2
#define  SIG_OBJECT_PARTICLEEMITTER_LIFETIME                 0xDB888510
#define  SIG_OBJECT_PARTICLEEMITTER_PERFRAME                 0xAEB674CB
#define  SIG_OBJECT_PARTICLEEMITTER_RADIUS                   0x59A4E59A
#define  SIG_OBJECT_PARTICLEEMITTER_STARTAT                  0x49FEBC06
#define  SIG_OBJECT_PARTICLEEMITTER_TYPE                     0xDF422CEF
#define  SIG_OBJECT_PATH_POSITION                            0xD348E57B
#define  SIG_OBJECT_PATH_ROTATION                            0x2335C825
#define  SIG_OBJECT_PATHS                                    0xBF7B0FE4
#define  SIG_OBJECT_PATH_SCALING                             0x9154F2AE
#define  SIG_OBJECT_PATH_SEGMENT                             0x8EB5FC70
#define  SIG_OBJECT_PRIMITIVE                                0xA61E4EB4
#define  SIG_OBJECT_PRIMITIVE_CONE                           0x14E5A54F
#define  SIG_OBJECT_PRIMITIVE_CONE_BASE                      0x9702EE7A
#define  SIG_OBJECT_PRIMITIVE_CUBE                           0xC1DBB750
#define  SIG_OBJECT_PRIMITIVE_CUBE_BASE                      0xE162A15B
#define  SIG_OBJECT_PRIMITIVE_CYLINDER                       0x64B5FE9F
#define  SIG_OBJECT_PRIMITIVE_CYLINDER_BASE                  0x0E70CBA3
#define  SIG_OBJECT_PRIMITIVE_PLANE                          0x38CD7589
#define  SIG_OBJECT_PRIMITIVE_PLANE_BASE                     0xB0C7C9BC
#define  SIG_OBJECT_PRIMITIVE_SPHERE                         0xBB3D1FB3
#define  SIG_OBJECT_PRIMITIVE_SPHERE_BASE                    0x1357622C
#define  SIG_OBJECT_PRIMITIVE_TORUS                          0x033C5DCC
#define  SIG_OBJECT_PRIMITIVE_TORUS_BASE                     0xFF404DC2
#define  SIG_OBJECT_PRIMITIVE_TUBE                           0x36425F0F
#define  SIG_OBJECT_PRIMITIVE_TUBE_BASE                      0xA620CEE2
#define  SIG_OBJECTS                                         0x15DB4DF2
#define  SIG_OBJECT_SCENE                                    0x4BBB8318
#define  SIG_OBJECTS_DECLARE                                 0x18686129
#define  SIG_OBJECTS_DEFINE                                  0x90B6ADBE
#define  SIG_OBJECT_SKIN                                     0xC5078055
#define  SIG_OBJECT_SPLINE                                   0x52A0AE8B
#define  SIG_OBJECT_SPLINE_GEOMETRY                          0x1B9C4060
#define  SIG_OBJECT_SPLINE_GEOMETRY_POINTS                   0x0958332F
#define  SIG_OBJECT_SPLINE_GEOMETRY_SEGMENTS                 0x1073F938
#define  SIG_OBJECT_SPLINEREVOLVER                           0xE7BFEC49
#define  SIG_OBJECT_SPLINEREVOLVER_GEOMETRY                  0x9549096A
#define  SIG_OBJECT_SUBDIVIDER                               0x563EEBF5
#define  SIG_OBJECT_SUBDIVIDER_LEVEL                         0x44314624
#define  SIG_OBJECT_SUBDIVIDER_SCULPTMAP_ENTRY               0xB7148EE8
#define  SIG_OBJECT_SUBDIVIDER_SCULPTMAP_FACEID              0x1C94927E
#define  SIG_OBJECT_SUBDIVIDER_SCULPTMAP_GEOMETRY            0x2F1DD051
#define  SIG_OBJECT_SUBDIVIDER_SCULPTMAPS                    0x84237D90
#define  SIG_OBJECT_SUBDIVIDER_SCULPTMAPS_RESOLUTION         0x03DEB5A7
#define  SIG_OBJECT_SUBDIVIDER_SYNC                          0x9D54E01B
#define  SIG_OBJECT_SYMMETRY                                 0xA1549C03
#define  SIG_OBJECT_SYMMETRY_MERGELIMIT                      0xEE05C709
#define  SIG_OBJECT_SYMMETRY_PLANE                           0x14831DB2
#define  SIG_OBJECT_TAG_ENTRY                                0x862B7814
#define  SIG_OBJECT_TAGS                                     0x7BDC2424
#define  SIG_OBJECT_TAG_TRACKER                              0xB996C6D2
#define  SIG_OBJECT_TAG_TRACKER_ORIENTATION                  0xA751479B
#define  SIG_OBJECT_TAG_TRACKER_TARGET                       0xA03FA14C
#define  SIG_OBJECT_TAG_VIBRATE                              0x507B1F93
#define  SIG_OBJECT_TAG_VIBRATE_FLAGS_ROTATION               0x869A33A1
#define  SIG_OBJECT_TAG_VIBRATE_FLAGS_SCALING                0x67A3993B
#define  SIG_OBJECT_TAG_VIBRATE_FLAGS_TRANSLATION            0x2FBD01A7
#define  SIG_OBJECT_TAG_VIBRATE_FREQUENCY                    0x3635D6C9
#define  SIG_OBJECT_TAG_VIBRATE_TRANSFORMATION               0xF4CDAC2F
#define  SIG_OBJECT_TEXT                                     0x4C5FABF0
#define  SIG_OBJECT_TEXT_FONT                                0x45FE1B68
#define  SIG_OBJECT_TEXT_FONT_FACE                           0xF6C46584
#define  SIG_OBJECT_TEXT_FONT_FILE                           0x524504E3
#define  SIG_OBJECT_TEXT_FONT_SIZE                           0xA477BF33
#define  SIG_OBJECT_TEXT_ROUNDNESS                           0xA62975B7
#define  SIG_OBJECT_TEXT_STRING                              0x4A9928EA
#define  SIG_OBJECT_TEXT_THICKNESS                           0x19819FB5
#define  SIG_OBJECT_TEXTURE_ENTRY                            0xE55DFF11
#define  SIG_OBJECT_TEXTURE_MATERIAL                         0x99AA0A59
#define  SIG_OBJECT_TEXTURE_RESTRICT                         0x6A0C4C55
#define  SIG_OBJECT_TEXTURES                                 0xD8CCD5B3
#define  SIG_OBJECT_TEXTURE_UVMAP                            0x7F6690DF
#define  SIG_OBJECT_TRANSFORMATION                           0x032337DC
#define  SIG_OBJECT_UVMAP_ENTRY                              0x421863FA
#define  SIG_OBJECT_UVMAP_FLAGS                              0x1562ED1C
#define  SIG_OBJECT_UVMAP_NAME                               0x319D470A
#define  SIG_OBJECT_UVMAP_PROJECTION                         0x3130507A
#define  SIG_OBJECT_UVMAP_RADIUS                             0x0D43B328
#define  SIG_OBJECT_UVMAPS                                   0xA51EEC38
#define  SIG_OBJECT_UVMAP_TRANSFORMATION                     0x69781F09
#define  SIG_OBJECT_UVMAP_UVSETS                             0xCF19BC88
#define  SIG_OBJECT_WIREFRAME                                0x40AFF65E
#define  SIG_OBJECT_WIREFRAME_ALGO                           0x012D8C08
#define  SIG_OBJECT_WIREFRAME_GEOMETRY                       0x9D0046B3
#define  SIG_ROOT                                            0x44335347
#define  SIG_ROOT_COMMENT                                    0xEEC76AC0
#define  SIG_ROOT_VERSION                                    0x475DDCE9
#define  SIG_ROOT_VERSION_APP                                0xC5BF91AC
#define  SIG_ROOT_VERSION_FILE                               0x7A68906E
#define  SIG_SCENE_FPS                                       0xD8E3C3BF

#endif
