#ifndef _SIGNATURES_H_
#define _SIGNATURES_H_

/* This file is auto generated */
/* Chunk IDs are created by using cksum on signature names */
/* Hence, please do not change signature names */

#define  SIG_CHANNEL                                    0x7EC2A570
#define  SIG_CHANNEL_IMAGE                              0x4EEB9C3F
#define  SIG_CHANNEL_PROCEDURAL                         0xFFC16160
#define  SIG_CHANNEL_PROCEDURAL_BRICK                   0xFA7B27F9
#define  SIG_CHANNEL_PROCEDURAL_BRICK_COLORS            0x994D644E
#define  SIG_CHANNEL_PROCEDURAL_BRICK_GEOMETRY          0x608C2AA8
#define  SIG_CHANNEL_PROCEDURAL_CHESS                   0x693BF181
#define  SIG_CHANNEL_PROCEDURAL_CHESS_COLORS            0x5CF5F21C
#define  SIG_CHANNEL_PROCEDURAL_CHESS_GEOMETRY          0x391F1ECF
#define  SIG_CHANNEL_PROCEDURAL_NOISE                   0x5555DA0A
#define  SIG_CHANNEL_PROCEDURAL_NOISE_COLORPAIR_COUNT   0x1008CAAB
#define  SIG_CHANNEL_PROCEDURAL_NOISE_COLORPAIRS        0x79814FB5
#define  SIG_CHANNEL_PROCEDURAL_NOISE_GRADIENTS         0xF33D8529
#define  SIG_CHANNEL_PROCEDURAL_NOISE_INTERPOLATION     0xDB77D998
#define  SIG_CHANNEL_PROCEDURAL_NOISE_OCTAVES           0x961160AB
#define  SIG_CHANNEL_PROCEDURAL_NOISE_THRESHOLDS        0xBF93F08B
#define  SIG_CHANNEL_PROCEDURAL_RESOLUTION              0xEE216EAF
#define  SIG_CHANNEL_SOLID                              0x6393699E
#define  SIG_EXTENSION_ENTRY                            0xE4C94E11
#define  SIG_EXTENSIONS                                 0x22457A87
#define  SIG_MATERIAL_ALPHA                             0x563A65EF
#define  SIG_MATERIAL_BUMP                              0x9679768A
#define  SIG_MATERIAL_BUMP_STRENGTH                     0x2A823612
#define  SIG_MATERIAL_DIFFUSE                           0xAF327CA2
#define  SIG_MATERIAL_DISPLACEMENT                      0xA094CAED
#define  SIG_MATERIAL_DISPLACEMENT_STRENGTH             0x0FB07028
#define  SIG_MATERIAL_ENTRY                             0xD8A97057
#define  SIG_MATERIAL_FLAGS                             0x8FD3FEB1
#define  SIG_MATERIAL_NAME                              0x9B8F73CE
#define  SIG_MATERIAL_REFLECTION                        0x2ED1D57E
#define  SIG_MATERIAL_REFLECTION_STRENGTH               0xA6E27549
#define  SIG_MATERIAL_REFRACTION                        0xF7116533
#define  SIG_MATERIAL_REFRACTION_STRENGTH               0xDBF22C46
#define  SIG_MATERIALS                                  0x09ABD5AC
#define  SIG_MATERIAL_SPECULAR                          0xCE7F7484
#define  SIG_MATERIAL_SPECULAR_LEVEL                    0x24CA1ADB
#define  SIG_MATERIAL_SPECULAR_SHININESS                0x92BEF4DC
#define  SIG_OBJECT_ACTIVE                              0x1E4FEB75
#define  SIG_OBJECT_BONE                                0x58B4AB43
#define  SIG_OBJECT_BONE_FIXING                         0x37806762
#define  SIG_OBJECT_BONE_FIXING_TRANSFORMATION          0xEF18142E
#define  SIG_OBJECT_BONE_LENGTH                         0xB876D5B8
#define  SIG_OBJECT_BONE_RIG_BINDMATRIX                 0xC9223A6B
#define  SIG_OBJECT_BONE_RIG_ENTRY                      0x0BED790B
#define  SIG_OBJECT_BONE_RIGS                           0x6A4F8B22
#define  SIG_OBJECT_BONE_RIG_SKINMATRIX                 0xA610F6C4
#define  SIG_OBJECT_BONE_RIG_WEIGHTGROUP                0x531902FA
#define  SIG_OBJECT_CAMERA                              0x590154D0
#define  SIG_OBJECT_CAMERA_FOCAL                        0x3B0925B4
#define  SIG_OBJECT_ENTRY                               0x08CAC424
#define  SIG_OBJECT_FFD                                 0xAAB09BB7
#define  SIG_OBJECT_FFD_GEOMETRY                        0x3E1B16CA
#define  SIG_OBJECT_FFD_UVW                             0x96C70372
#define  SIG_OBJECT_FFD_VERTICES                        0x2815E438
#define  SIG_OBJECT_IDENTITY                            0xFE404903
#define  SIG_OBJECT_IDENTITY_NAME                       0x647F2371
#define  SIG_OBJECT_IDENTITY_PARENT                     0x34D92405
#define  SIG_OBJECT_IDENTITY_TYPE                       0x5173F267
#define  SIG_OBJECT_KEY_DATA                            0x577054D2
#define  SIG_OBJECT_KEY_DATA_MORPHER                    0xDF460185
#define  SIG_OBJECT_KEY_DATA_MORPHER_SLOT_ENTRY         0xFCC8B531
#define  SIG_OBJECT_KEY_DATA_MORPHER_SLOT_ID            0xDC52A02D
#define  SIG_OBJECT_KEY_DATA_MORPHER_SLOT_OPTIONS       0xDE59024D
#define  SIG_OBJECT_KEY_DATA_MORPHER_SLOT_OPTIONS_RATE  0x8A5ABB23
#define  SIG_OBJECT_KEY_DATA_MORPHER_SLOTS              0x603888CC
#define  SIG_OBJECT_KEY_ENTRY                           0xAA0C1CF8
#define  SIG_OBJECT_KEY_FLAGS                           0xFD76921E
#define  SIG_OBJECT_KEY_FLAGS_DATA                      0xC88F404E
#define  SIG_OBJECT_KEY_FLAGS_ROTATION                  0x3BCBC4FF
#define  SIG_OBJECT_KEY_FLAGS_SCALING                   0x7C3112B2
#define  SIG_OBJECT_KEY_FLAGS_TRANSLATION               0x65E5E57B
#define  SIG_OBJECT_KEY_LOOP                            0x0FEC17BD
#define  SIG_OBJECT_KEYS                                0xBBE0F54D
#define  SIG_OBJECT_KEY_TRANSFORMATION                  0x499C5B71
#define  SIG_OBJECT_LIGHT                               0x9722B4F3
#define  SIG_OBJECT_LIGHT_AMBIENT                       0x5857EAF8
#define  SIG_OBJECT_LIGHT_DIFFUSE                       0x95B25CFB
#define  SIG_OBJECT_LIGHT_INTENSITY                     0x482032B2
#define  SIG_OBJECT_LIGHT_SHADOW                        0xF365A4D5
#define  SIG_OBJECT_LIGHT_SHADOW_CASTING                0xB34778F4
#define  SIG_OBJECT_LIGHT_SHADOW_COLOR                  0x45301A77
#define  SIG_OBJECT_LIGHT_SPECULAR                      0x4F876F5D
#define  SIG_OBJECT_LIGHT_SPOT                          0x94A8DF01
#define  SIG_OBJECT_MESH                                0xB5C6334F
#define  SIG_OBJECT_MESH_FACEGROUP_ENTRY                0xE78FE5CD
#define  SIG_OBJECT_MESH_FACEGROUP_FACES                0x303DDFB0
#define  SIG_OBJECT_MESH_FACEGROUP_NAME                 0xA7956F45
#define  SIG_OBJECT_MESH_FACEGROUPS                     0x0FB5B31E
#define  SIG_OBJECT_MESH_GEOMETRY                       0xB8E24649
#define  SIG_OBJECT_MESH_GEOMETRY_POLYGONS              0x66659F93
#define  SIG_OBJECT_MESH_GEOMETRY_VERTICES              0xDC54DB9D
#define  SIG_OBJECT_MESH_GOURAUDLIMIT                   0xB1312AD6
#define  SIG_OBJECT_MESH_WEIGHTGROUP_ENTRY              0x2038ABB8
#define  SIG_OBJECT_MESH_WEIGHTGROUP_NAME               0x5ABC431A
#define  SIG_OBJECT_MESH_WEIGHTGROUPS                   0x48A48DC1
#define  SIG_OBJECT_MESH_WEIGHTGROUP_WEIGHTS            0x41E78C3A
#define  SIG_OBJECT_MORPHER                             0x66AB5D49
#define  SIG_OBJECT_MORPHER_MESHPOSE_ENTRY              0x36A725F1
#define  SIG_OBJECT_MORPHER_MESHPOSE_GEOMETRY           0x889B5F26
#define  SIG_OBJECT_MORPHER_MESHPOSE_NAME               0x6973ADDF
#define  SIG_OBJECT_MORPHER_MESHPOSES                   0xDFAC03AC
#define  SIG_OBJECT_MORPHER_MESHPOSE_SLOT_ID            0x9FCAD991
#define  SIG_OBJECT_MORPHER_RESETPOSITIONS              0x14792184
#define  SIG_OBJECT_MORPHER_VERTEX_COUNT                0xD1AA812A
#define  SIG_OBJECT_NULL                                0x0E72D315
#define  SIG_OBJECT_PRIMITIVE                           0xA61E4EB4
#define  SIG_OBJECT_PRIMITIVE_CONE                      0x14E5A54F
#define  SIG_OBJECT_PRIMITIVE_CUBE                      0xC1DBB750
#define  SIG_OBJECT_PRIMITIVE_CYLINDER                  0x64B5FE9F
#define  SIG_OBJECT_PRIMITIVE_PLANE                     0x38CD7589
#define  SIG_OBJECT_PRIMITIVE_SPHERE                    0xBB3D1FB3
#define  SIG_OBJECT_PRIMITIVE_TORUS                     0x033C5DCC
#define  SIG_OBJECTS                                    0x15DB4DF2
#define  SIG_OBJECT_SCENE                               0x4BBB8318
#define  SIG_OBJECT_SPLINE                              0x52A0AE8B
#define  SIG_OBJECT_SPLINE_GEOMETRY                     0x1B9C4060
#define  SIG_OBJECT_SPLINE_GEOMETRY_POINTS              0x0958332F
#define  SIG_OBJECT_SPLINE_GEOMETRY_SEGMENTS            0x1073F938
#define  SIG_OBJECT_SPLINEREVOLVER                      0xE7BFEC49
#define  SIG_OBJECT_SPLINEREVOLVER_GEOMETRY             0x9549096A
#define  SIG_OBJECT_SUBDIVIDER                          0x563EEBF5
#define  SIG_OBJECT_SUBDIVIDER_LEVEL                    0x44314624
#define  SIG_OBJECT_SYMMETRY                            0xA1549C03
#define  SIG_OBJECT_SYMMETRY_MERGELIMIT                 0xEE05C709
#define  SIG_OBJECT_SYMMETRY_PLANE                      0x14831DB2
#define  SIG_OBJECT_TEXT                                0x4C5FABF0
#define  SIG_OBJECT_TEXT_FONT                           0x45FE1B68
#define  SIG_OBJECT_TEXT_FONT_FACE                      0xF6C46584
#define  SIG_OBJECT_TEXT_FONT_FILE                      0x524504E3
#define  SIG_OBJECT_TEXT_FONT_SIZE                      0xA477BF33
#define  SIG_OBJECT_TEXT_ROUNDNESS                      0xA62975B7
#define  SIG_OBJECT_TEXT_STRING                         0x4A9928EA
#define  SIG_OBJECT_TEXT_THICKNESS                      0x19819FB5
#define  SIG_OBJECT_TEXTURE_ENTRY                       0xE55DFF11
#define  SIG_OBJECT_TEXTURE_MATERIAL                    0x99AA0A59
#define  SIG_OBJECT_TEXTURE_RESTRICT                    0x6A0C4C55
#define  SIG_OBJECT_TEXTURES                            0xD8CCD5B3
#define  SIG_OBJECT_TEXTURE_UVMAP                       0x7F6690DF
#define  SIG_OBJECT_TRANSFORMATION                      0x032337DC
#define  SIG_OBJECT_UVMAP_ENTRY                         0x421863FA
#define  SIG_OBJECT_UVMAP_FLAGS                         0x1562ED1C
#define  SIG_OBJECT_UVMAP_NAME                          0x319D470A
#define  SIG_OBJECT_UVMAP_PROJECTION                    0x3130507A
#define  SIG_OBJECT_UVMAP_RADIUS                        0x0D43B328
#define  SIG_OBJECT_UVMAPS                              0xA51EEC38
#define  SIG_OBJECT_UVMAP_TRANSFORMATION                0x69781F09
#define  SIG_OBJECT_UVMAP_UVSETS                        0xCF19BC88
#define  SIG_OBJECT_WIREFRAME                           0x40AFF65E
#define  SIG_OBJECT_WIREFRAME_ALGO                      0x012D8C08
#define  SIG_OBJECT_WIREFRAME_GEOMETRY                  0x9D0046B3
#define  SIG_ROOT                                       0x44335347
#define  SIG_ROOT_COMMENT                               0xEEC76AC0
#define  SIG_ROOT_VERSION                               0x475DDCE9
#define  SIG_ROOT_VERSION_APP                           0xC5BF91AC
#define  SIG_ROOT_VERSION_FILE                          0x7A68906E

#endif
